#!/usr/bin/env python3
# this program combindes all js files into one js file for easier imports
import os

path = "./src/"
output = "./bin/RapidElements.js"
content = ""
for x in os.listdir(path):
    if x.endswith(".js"):
        with open(f"{path+x}","r") as f:
            content += f.read()+"\n"

with open(output,"w") as f:
    f.write(content)
